package com.csust.soleprecision.navigation

enum class Maneuver(
    val wireCode: Int,
    val spokenLabel: String,
) {
    UNKNOWN(0, "Continue with caution"),
    STRAIGHT(1, "Continue straight"),
    SLIGHT_LEFT(2, "Bear left"),
    LEFT(3, "Turn left"),
    SHARP_LEFT(4, "Turn sharply left"),
    SLIGHT_RIGHT(5, "Bear right"),
    RIGHT(6, "Turn right"),
    SHARP_RIGHT(7, "Turn sharply right"),
    U_TURN(8, "Make a U-turn"),
    CROSSWALK(9, "Crosswalk ahead"),
    STAIRS(10, "Stairs ahead"),
    ELEVATOR(11, "Elevator ahead"),
    ARRIVED(12, "Destination reached"),
    OVERPASS(13, "Footbridge ahead"),
    UNDERPASS(14, "Underpass ahead"),
    ESCALATOR(15, "Escalator ahead"),
    RAMP(16, "Ramp ahead"),
    BRIDGE(17, "Bridge ahead"),
    TUNNEL(18, "Tunnel ahead"),
    PEDESTRIAN_WAY(19, "Pedestrian path ahead"),
    ENTER_BUILDING(20, "Enter the building"),
    LEAVE_BUILDING(21, "Leave the building"),
    SUBWAY_PASSAGE(22, "Subway passage ahead"),
    FERRY(23, "Ferry connection ahead"),
    ROUNDABOUT(24, "Roundabout ahead"),
    PARK_OR_SQUARE(25, "Open pedestrian area ahead"),
}
